{{- if and .Values.service.enabled (not .Values.cronjob.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "seat-service.name" . }}
  labels: {{ include "seat-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "seat-service.labels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
