nameOverride: frontend
image:
  repository: seat-booking/frontend
  tag: "64fcbb5c79245ba20a40f47207091f26f4c8bf1c"
replicaCount: 1
port: 8080
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
probes:
  liveness: "/"
  readiness: "/"
service:
  enabled: true
  port: 80
ingress:
  enabled: true
  path: /
  pathType: Prefix
