nameOverride: settlement
image:
  repository: seat-booking/settlement
  tag: "073c9e9f9f7fd655957a27fee2dd54ed93c4ddbd"
cronjob:
  enabled: true
  schedule: "0 2 * * *"
service:
  enabled: false
env:
  DB_HOST: postgres.booking.svc
  DB_PORT: "5432"
  DB_NAME: booking_db
  DB_USER: booking
  DB_PASSWORD: booking
