image:
  repository: "402631154447.dkr.ecr.ap-south-1.amazonaws.com/seat-booking/payment-worker"
  tag: v2
serviceAccount:
  create: true
  roleArn: "arn:aws:iam::402631154447:role/seat-booking-payment-worker-sqs"
env:
  QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/402631154447/payments"
  AWS_REGION: "ap-south-1"
  QUEUE_ENDPOINT: ""
keda:
  enabled: true
  authMode: irsa
  queueURL: "https://sqs.ap-south-1.amazonaws.com/402631154447/payments"
  awsRegion: "ap-south-1"
