nameOverride: payment-worker
image:
  repository: seat-booking/payment-worker
  tag: "073c9e9f9f7fd655957a27fee2dd54ed93c4ddbd"
replicaCount: 1
port: 8080
env:
  BFF_URL: http://booking-bff.booking.svc:8080
  INTERNAL_TOKEN: internal-devsecret
  QUEUE_ENDPOINT: http://elasticmq.booking.svc:9324
  QUEUE_URL: http://elasticmq.booking.svc:9324/queue/payments
  AWS_REGION: elasticmq
  GATEWAY_DELAY_SECONDS: "3"
probes:
  liveness: "/"
  readiness: "/"
service:
  enabled: true
ingress:
  enabled: false
