nameOverride: settlement
image:
  repository: seat-booking/settlement
  tag: "64fcbb5c79245ba20a40f47207091f26f4c8bf1c"
cronjob:
  enabled: true
  schedule: "0 2 * * *"
service:
  enabled: false
env:
  DB_HOST: postgres.booking.svc
  DB_PORT: "5432"
  DB_NAME: booking_db
  DB_USER: booking
  DB_PASSWORD: booking
