nameOverride: seatmap
image:
  repository: seat-booking/seatmap
  tag: "073c9e9f9f7fd655957a27fee2dd54ed93c4ddbd"
replicaCount: 1
port: 8080
env:
  INVENTORY_URL: http://inventory.booking.svc:8080
  REDIS_URL: redis://redis.booking.svc:6379/0
probes:
  liveness: /healthz
  readiness: /readyz
service:
  enabled: true
ingress:
  enabled: false
