nameOverride: seatmap
image:
  repository: seat-booking/seatmap
  tag: "4033dbb63d4437a6b7e001f78a691da8ad09f3a6"
replicaCount: 1
port: 8080
env:
  INVENTORY_URL: http://inventory.booking.svc:8080
  REDIS_URL: redis://redis.booking.svc:6379/0
probes:
  liveness: /healthz
  readiness: /readyz
service:
  enabled: true
ingress:
  enabled: false
